### PR TITLE
Pod spec changes to Fix incompatible issue

### PR DESCRIPTION
**Pull request by Streel88**
This fixes 
https://github.com/Cocoanetics/BarCodeKit/issues/4

### CODE REVIEW

**Comment by cbarbera80** [comment]
could you merge, please?

**Comment by odrobnik** [comment]
@cbarbera80 what about the second issue you mentioned in #4?

**Comment by cbarbera80** [comment]
hmmm i'haven't mentioned anything ;)

**Comment by Streel88** [comment]
Waiting on @odrobnik to merge if he is happy with the change

**Pull request merged**
