### PR TITLE
added possibility to state direct size of the barcode (note: this is …

### PR DESCRIPTION
**Pull request by mkoetzing**
…for higher resolution of the needed barcode, no restriction anymore)

### CODE REVIEW

**Comment by odrobnik** [comment]
@mkoetzing Please fold the `sizeWithDirectOptions` into the `sizeWithRenderOptions` function so that the determining of the size is in this single place. You can have your overrides at the top and if they are not set, you fall back to the calculated minimum size. There should only be a single method.

**Comment by mkoetzing** [comment]
good point, will do that

**Comment by mkoetzing** [comment]
done and updated the demo-app (but the second commit does not necessarily need to be pulled into the develop-branch)

**Comment by odrobnik** [comment]
Well done! Please also add the new options to the documentation comments in the header.

I see that you seem to need both width and height for them to have an effect... Wouldn't it be better to have a CGSize item in there (via NSValue) or by allowing to set only one of them - for cases where the barcode has a built-in aspect ratio and the other value could then be calculated from the aspect ratio if it is non-zero.

**Comment by mkoetzing** [comment]
yes you are right - i changed it to whether which option is set and added the documentation of the new options

**Comment by mkoetzing** [comment]
is it possible to get a new pods version of the barcodekit with these changes?

**Comment by mkoetzing** [comment]
thank you

**Pull request merged**
