### PR TITLE
Add SPM support

### PR DESCRIPTION
**Pull request by marcmatta**
This pull request adds SPM support for this library but it only handles iOS for now.

The swift Package is called BarCodeKitWrapper.

The package source files are under a folder called "Source" holding the wrapped xcFramework having iphoneos and iphonesimulator generated static libraries and their respective public headers added under the "include" folder.

The BarCodeKit (iOS) target has been updated in order to copy the public headers needed while generating the static library.

### CODE REVIEW

**Comment by marcmatta** [comment]
Mac support can be added by updating the Package.swift and the spm-build.sh in order to build macos architecture into the xcFramework.

This will require running spm-build.sh manually after making the appropriate changes by running the following Terminal command:

`bash spm-build.sh`

**Comment by marcmatta** [comment]
@odrobnik it would be nice to have this commit tagged and released once approved so that we can start using SPM to link against this library. Thanks!

**Comment by odrobnik** [comment]
why is that implemented not as a source package? that would make the whole process much simpler and it would work out of the box for iOS and Mac.

**Comment by marcmatta** [comment]
This was the only way i was able to expose the ObjC code. If you can guide me into how to make the source package, I can make the updates / test and update this pull request.

**Comment by marcmatta** [comment]
My knowledge in creating SPM packages is somewhat limited and this is how i could make it work with ObjC.

**Comment by odrobnik** [comment]
I make all my ObjC frameworks into SPM packages like this: https://github.com/Cocoanetics/DTKeychain

**Comment by marcmatta** [comment]
I will review this and make it similar. Thanks!

**Comment by marcmatta** [comment]
So you don't mind moving the headers to an "include" folder?

**Comment by odrobnik** [comment]
those are not moved, but they are linux soft links

**Comment by odrobnik** [comment]
this way they get picked up by the package, but still are present in the original location.

**Comment by marcmatta** [comment]
@odrobnik can I get some help with this please? I have followed a similar structure but when i test linking against this package from a test project i get an error:

could not build Objective-C module 'BarCodeKit'

By the way, I get errors adding the DTKeychain project in my test app. So i followed the DTCoreText as an example as it looked similar and it works well.

**Comment by odrobnik** [comment]
I've begun to look at this... the first thing I see is that it cannot find NSImage in macOS code. So we definitely need to separate macOS and iOS code into separate folders

**Comment by odrobnik** [comment]
also you seem to have deleted the UIImage+BarCodeKit and NSImage+BarCodeKit... those are now dead links in Xcode project.

**Pull request merged**
